# Generated by Django 4.2.4 on 2023-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(choices=[('1w', '1win'), ('1w', '1xbet')], default='1x', max_length=4)),
                ('code', models.CharField(max_length=5)),
                ('img', models.ImageField(upload_to='uploads/%Y/%M/%d')),
                ('status', models.CharField(choices=[('V', 'Validé'), ('N', 'Accepté'), ('P', 'Perdu')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MailParieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
