# Generated by Django 4.2.4 on 2023-09-12 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0002_coupon_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 19, 12, 55, 737633, tzinfo=datetime.timezone.utc)),
        ),
    ]
