# Generated by Django 4.2.4 on 2023-09-12 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0003_alter_coupon_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
