# Generated by Django 4.2.4 on 2023-09-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0005_alter_coupon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='bookmaker',
            field=models.CharField(choices=[('1w', '1win'), ('1x', '1xbet')], default='1x', max_length=4),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
